[#CO-2009] add a gh workflow so tests are run
BloomAndWild/klarna_client pull request #11
Opened 2024-04-30 09:55 UTC by mariacastro96

2024-04-30 10:31 UTC, cuotos requested changes

2024-04-30 10:31 UTC, cuotos commented on .github/workflows/run-tests.yml
> +
```suggestion
  pull_request:
```

i think this will be enough

2024-04-30 10:31 UTC, cuotos commented on .github/workflows/run-tests.yml
> +  cancel-in-progress: true
probably overkill for this as the tests will be quick. Id just take it out unless its actually needed later

2024-04-30 10:31 UTC, cuotos commented on .github/workflows/run-tests.yml
> +      DOCKER_NETWORK: bw-net-${{github.event.pull_request.head.sha}}-tests
what is this for?

2024-04-30 10:33 UTC, cuotos commented on .github/workflows/run-tests.yml
> +          ruby-version: '2.3.0'
monolith uses 3.1.4. If its the monolith using this Gem, then there is no reason to not be on _at least_ the same ruby version.

2.3 is unmaintained as of 5 years ago

2024-04-30 10:35 UTC, mariacastro96 commented on .github/workflows/run-tests.yml
> +          ruby-version: '2.3.0'
Yes. we have a card to update the ruby version on this gem. we will then also add specs that are valid
is it ok to leave like this for now?

2024-04-30 10:35 UTC, mariacastro96 commented on .github/workflows/run-tests.yml
> +          description: "This step checks out the latest code from the repository."
thank you

2024-04-30 10:36 UTC, mariacastro96 commented on .github/workflows/run-tests.yml
> +      DOCKER_NETWORK: bw-net-${{github.event.pull_request.head.sha}}-tests
i'm not sure, i think i will remove

2024-04-30 10:36 UTC, mariacastro96 commented on .github/workflows/run-tests.yml
> +  cancel-in-progress: true
the whole concurrency block?

2024-04-30 10:36 UTC, cuotos commented on .github/workflows/run-tests.yml
> +        run: bundle exec rspec
have you tried running these steps locally. they fail due to not having a KLARNA_API_KEY and KLARNA_API_SECRET env var set

2024-04-30 10:37 UTC, mariacastro96 commented on .github/workflows/run-tests.yml
> +        run: bundle exec rspec
even with those the specs will fail but that is true, i will set those up before. thank you

2024-04-30 15:35 UTC, alypeng approved these changes

2024-05-01 10:07 UTC, Eddie901 commented on spec/spec_helper.rb
> +# require 'capybara-screenshot/rspec'
Why uncomment here? Should we make those changes in the branch which removes the failing specs?

2024-05-01 10:08 UTC, Eddie901 approved these changes

2024-05-01 10:08 UTC, mariacastro96 commented on spec/spec_helper.rb
> +# require 'capybara-screenshot/rspec'
locally it wasn't running the spcs with that uncommented. given it's going anyways i thought it would be better to at least run them. can remove though if you want

2024-05-02 14:30 UTC, merged